In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/Users/prabalkhangura1gmail.com/Coding/Machine Learning/Ori/Evaluation-dataset.csv',header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Tires where delivered to the garage of my choi...,garage service positive,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Easy Tyre Selection Process, Competitive Prici...",garage service positive,value for money positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Very easy to use and good value for money.,value for money positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Really easy and convenient to arrange,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It was so easy to select tyre sizes and arrang...,location positive,value for money positive,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(10132, 15)

In [4]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [5]:
arr=['Column_'+str(i) for i in range(1,15)]
new=['Sentence']+arr
df.columns=new

In [6]:
df.head()

,Sentence,Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8,Column_9,Column_10,Column_11,Column_12,Column_13,Column_14
0,Tires where delivered to the garage of my choi...,garage service positive,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Easy Tyre Selection Process, Competitive Prici...",garage service positive,value for money positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Very easy to use and good value for money.,value for money positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Really easy and convenient to arrange,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It was so easy to select tyre sizes and arrang...,location positive,value for money positive,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
review={}

for i in df.columns:
    if i!='Sentence':
        x=df[i].dropna()
        for l in x:
            if l not in review.keys():
                review[l]=1
            else:
                review[l]+=1

In [8]:
review

{'garage service positive': 2031,
 'value for money positive': 4780,
 'ease of booking positive': 1187,
 'location positive': 1063,
 'length of fitting positive': 657,
 'ease of booking negative': 227,
 'tyre quality positive': 434,
 'garage service negative': 423,
 'wait time negative': 135,
 'delivery punctuality positive': 453,
 'wait time positive': 274,
 'location negative': 27,
 'damage negative': 127,
 'extra charges positive': 85,
 'value for money negative': 136,
 'mobile fitter positive': 225,
 'advisor/agent service positive': 202,
 'facilities positive': 33,
 'change of time negative': 42,
 'extra charges negative': 46,
 'late notice negative': 76,
 'discounts positive': 115,
 'delivery punctuality negative': 250,
 'refund not actioned positive': 1,
 'change of date negative': 277,
 'booking confusion negative': 119,
 'advisoragent service positive': 233,
 'advisor/agent service negative': 47,
 'advisoragent service negative': 125,
 'incorrect tyres sent negative': 70,
 'tyre quality negative': 40,
 'response time negative': 77,
 'refund positive': 28,
 "mobile fitter didn't arrive negative": 14,
 'no stock negative': 42,
 'change of date positive': 21,
 'refund not actioned negative': 14,
 'call wait time negative': 24,
 'refund negative': 25,
 'discount not applied negative': 9,
 'length of fitting negative': 109,
 ' telephone help avaiable if required.': 1,
 'balancing negative': 24,
 'mobile fitter negative': 28,
 ' good service': 1,
 ' great price.': 1,
 ' fitting took a long time.': 1,
 'facilities negative': 18,
 ' keep it up! Will definitely buy from you again.': 1,
 " they looked grey and old (but unused) not at all how new tyres normally look. Not surprising when I inspected the 'Dot Date' and it was 4517 (ie tyres manufactured in week 45 of 2017.Queried this with [REDACTED] who told me that they have many different suppliers and do not check the age of the tyres.They could re-order but no guarantee that the replacements would be any newer. Not at all happy and requested a refund which they say they will do.": 1,
 'discounts negative': 28,
 'response time positive': 34,
 ' good communication': 1,
 ' good price': 2,
 'refund timescale negative': 10,
 ' tje garage i choice to go to in order to have the tyres fitted was nit that good and i certainly will not be using them again.': 1,
 ' good local fitting services': 1,
 ' simple to use website': 1,
 'tyre agedot code negative': 8,
 ' only 8 as the garage was unable to fit the tyres in the allotted time and I had to wait over an hour.': 1,
 ' Great garage fitted them': 1,
 ' really good prices': 1,
 'tyre agedot code positive': 2,
 'booking confusion positive': 2,
 ' ability to browse through various makes of tyres before making a decision': 1,
 ' easy to browse selection of tyres before making a choice': 1,
 ' hassle free': 1,
 ' the site is easy to use': 1,
 ')': 1,
 ' and both times have been good experiences.': 1,
 'failed payment negative': 5,
 'balancing positive': 14,
 ' staff were courteous': 1,
 'tyre age/dot code negative': 9,
 'refund timescale positive': 6,
 ' faster than dealerships to arrange supply and partnership with ATS works well .': 1,
 ' won’t be using anyone else.': 1,
 ' wide choice of tyres at great prices including delivery and fitting.': 1,
 ' good prices': 1,
 ' my tyre supplier of choice!.': 1,
 ' and an excellent service from the garage who fitted the tyre.': 1,
 ' the process was simple and quick.Regular offers make it easy to find premium tyres at decent prices.': 1,
 ' cheaper than anything else I have found by some way.': 1,
 " one tyre with dangerously low air pressure. Asked the garage to top up the tyre and check the other three. They did top up the one tyre but didn't bother to check the others. When I checked the tyres 10 minutes later all four tyres had varying pressures (from 29 to 37.5). I emailed both companies and have not received an apology from either. I will never use Lavender Motors again (they shouldn't be in business) and likely not [REDACTED].com either.": 1,
 'incorrect tyres sent positive': 2,
 ' clean reception area and free coffee': 1,
 ' prompt deliveries...': 1,
 ' easily navigable web site': 1,
 ' Garage was quick & efficient with fitting of tyres': 1,
 ' Cheapest price': 1,
 ' really friendly and efficient service.': 1,
 ' simple fitting procedure': 1,
 ' simple booking for fitting procedure.': 1,
 ' good range and competitive prices on website': 1,
 ' it feels more transparent than buying from a mechanic based on their opinion.': 1,
 'no issues': 1,
 ' recommended a great local shop for fitting': 1,
 "mobile fitter didn't arrive positive": 1,
 ' polite staff': 1,
 ' slick delivery service and good fitter.': 1,
 'change of time positive': 1,
 'discount not applied positive': 1,
 'failed payment positive': 1,
 'late notice positive': 1,
 'call wait time positive': 1,
 'no stock positive': 1}

In [9]:
list1 = []

for key, value in review.items():
        
    if value>30:
            
        list1.append(key)

list1

['garage service positive',
 'value for money positive',
 'ease of booking positive',
 'location positive',
 'length of fitting positive',
 'ease of booking negative',
 'tyre quality positive',
 'garage service negative',
 'wait time negative',
 'delivery punctuality positive',
 'wait time positive',
 'damage negative',
 'extra charges positive',
 'value for money negative',
 'mobile fitter positive',
 'advisor/agent service positive',
 'facilities positive',
 'change of time negative',
 'extra charges negative',
 'late notice negative',
 'discounts positive',
 'delivery punctuality negative',
 'change of date negative',
 'booking confusion negative',
 'advisoragent service positive',
 'advisor/agent service negative',
 'advisoragent service negative',
 'incorrect tyres sent negative',
 'tyre quality negative',
 'response time negative',
 'no stock negative',
 'length of fitting negative',
 'response time positive']

In [10]:
len(list1)

33

In [11]:
df.head()

,Sentence,Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8,Column_9,Column_10,Column_11,Column_12,Column_13,Column_14
0,Tires where delivered to the garage of my choi...,garage service positive,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Easy Tyre Selection Process, Competitive Prici...",garage service positive,value for money positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Very easy to use and good value for money.,value for money positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Really easy and convenient to arrange,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It was so easy to select tyre sizes and arrang...,location positive,value for money positive,ease of booking positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
def newdataframe(data):
    df1 = df.iloc[:, 1:]
    df2 = pd.DataFrame(index= range(0, df1.shape[0]), columns=list1)
    for i, row in df1.iterrows():
        
        subthemes = row.dropna().tolist()
        
        for sent in subthemes:
            
            df2.loc[i][sent] = 1
            

    df2 = df2.fillna(0)
    final_df = pd.DataFrame()
    final_df['Sentence'] = df['Sentence']
    for column in df2.columns:
        final_df[column] = df2[column]
    return final_df

In [13]:
final_df = newdataframe(df)
final_df.head()

,Sentence,garage service positive,value for money positive,ease of booking positive,location positive,length of fitting positive,ease of booking negative,tyre quality positive,garage service negative,wait time negative,...,booking confusion negative,advisoragent service positive,advisor/agent service negative,advisoragent service negative,incorrect tyres sent negative,tyre quality negative,response time negative,no stock negative,length of fitting negative,response time positive
0,Tires where delivered to the garage of my choi...,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Easy Tyre Selection Process, Competitive Prici...",1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Very easy to use and good value for money.,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Really easy and convenient to arrange,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,It was so easy to select tyre sizes and arrang...,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
import pandas as pd
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

corpus=[]
def preprocess(text):
    text = re.sub(r'<[^>]+>', '', text)  # Remove HTML tags
    text = re.sub(r'\d+', '', text)  # Remove digits
    text = text.lower()  # Lowercase
    tokens = word_tokenize(text)  # Tokenize
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stopwords.words('english')]  # Remove stopwords and lemmatize
    tokens=' '.join(tokens)
    corpus.append(tokens)
    return tokens

final_df['Sentence'] = final_df['Sentence'].apply(preprocess)

In [15]:
final_df.head()

,Sentence,garage service positive,value for money positive,ease of booking positive,location positive,length of fitting positive,ease of booking negative,tyre quality positive,garage service negative,wait time negative,...,booking confusion negative,advisoragent service positive,advisor/agent service negative,advisoragent service negative,incorrect tyres sent negative,tyre quality negative,response time negative,no stock negative,length of fitting negative,response time positive
0,"tire delivered garage choice , garage notified...",1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"easy tyre selection process , competitive pric...",1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,easy use good value money .,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,really easy convenient arrange,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,easy select tyre size arrange local fitting . ...,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
final_df.to_csv('experiment.csv')

In [17]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from sklearn.preprocessing import MultiLabelBinarizer

# Initialize the tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')


# Tokenize the text data
texts = final_df['Sentence'].tolist()
encodings = tokenizer(texts, truncation=True, padding=True, max_length=128)

# Convert labels to a binary matrix
mlb = MultiLabelBinarizer()
labels = final_df.drop(columns=['Sentence']).values
binary_labels = mlb.fit_transform(labels)

/Users/prabalkhangura1gmail.com/anaconda3/lib/python3.11/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/Users/prabalkhangura1gmail.com/anaconda3/lib/python3.11/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

In [20]:
from sklearn.metrics import hamming_loss, accuracy_score, precision_score, recall_score, f1_score

In [21]:
def compute_metrics(p):
    preds = p.predictions[0] if isinstance(p.predictions, tuple) else p.predictions
    preds = (preds > 0.5).astype(int)
    labels = p.label_ids
    
    hamming = hamming_loss(labels, preds)
    accuracy = accuracy_score(labels, preds)
    precision = precision_score(labels, preds, average='micro')
    recall = recall_score(labels, preds, average='micro')
    f1 = f1_score(labels, preds, average='micro')
    
    return {
        'hamming_loss': hamming,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
    }

In [22]:
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import BertForSequenceClassification, Trainer, TrainingArguments

class CustomDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.float)
        return item

    def __len__(self):
        return len(self.labels)

# Create the dataset
dataset = CustomDataset(encodings, binary_labels)

# Define training arguments
training_args = TrainingArguments(
     output_dir='./results',
    num_train_epochs=1,  # Reduce the number of epochs
    per_device_train_batch_size=16,  # Increase batch size
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
  
)

# Load the model
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=len(mlb.classes_), problem_type="multi_label_classification")

# Create the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    eval_dataset=dataset,
    compute_metrics=compute_metrics,
)

# Fine-tune the model
trainer.train()
eval_results = trainer.evaluate()
print(eval_results)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.bias', 'pre_classifier.weight', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/Users/prabalkhangura1gmail.com/anaconda3/lib/python3.11/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(

{'eval_loss': 0.08786339312791824, 'eval_hamming_loss': 0.02857283853138571, 'eval_accuracy': 0.9428543229372286, 'eval_precision': 0.9814217802305885, 'eval_recall': 0.9868681318681318, 'eval_f1': 0.9841374208925783, 'eval_runtime': 155.7676, 'eval_samples_per_second': 65.046, 'eval_steps_per_second': 4.07, 'epoch': 1.0}